// <auto-generated />
namespace mvcOne.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddingMoviesTable12 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingMoviesTable12));
        
        string IMigrationMetadata.Id
        {
            get { return "201809111444220_AddingMoviesTable12"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
